wikilang2iso = {'ko-kp': ['ko_Kore_KP', 'ko_Latn_KP'],
           'bn': ['bn_Latn_BD',
            'bn_Beng_NP',
            'bn_Beng_GB',
            'bn_Beng_BD',
            'bn_Beng_IN'],
           'ug': ['ug_Arab_CN', 'ug_Cyrl_MN', 'ug_Cyrl_KZ'],
           'kk': ['kk_Arab_MN',
            'kk_Arab_CN',
            'kk_Arab_AF',
            'kk_Latn_KZ',
            'kk_Cyrl_KZ',
            'kk_Arab_TR',
            'kk_Arab_IR'],
           'ee': ['ee_Latn_GH', 'ee_Latn_TG'],
           'tg-cyrl': ['tg_Cyrl_TJ'],
           'co': ['co_Latn_FR'],
           'tk': ['tk_Latn_IR', 'tk_Latn_TM', 'tk_Latn_AF'],
           'bg': ['bg_Cyrl_RO',
            'bg_Latn_BG',
            'bg_Cyrl_TR',
            'bg_Cyrl_MD',
            'bg_Cyrl_UA',
            'bg_Cyrl_GR',
            'bg_Cyrl_BG'],
           'ng': ['ng_Latn_NA'],
           'pa': ['pa_Guru_IN', 'pa_Arab_PK'],
           'ja': ['ja_Hira_JP',
            'ja_Kana_JP',
            'ja_Latn_JP',
            'ja_Jpan_JP',
            'ja_Latn_JP',
            'ja_Latn_JP'],
           'kk-cyrl': ['kk_Cyrl_KZ'],
           'bs': ['bs_Latn_BA', 'bs_Cyrl_BA'],
           'so': ['so_Latn_SO', 'so_Osma_SO'],
           'be': ['be_Cyrl_UA', 'be_Cyrl_BY', 'be_Latn_BY', 'be_Cyrl_PL'],
           'om': ['om_Latn_SO', 'om_Latn_ET', 'om_Latn_KE'],
           'dv': ['dv_Latn_MV', 'dv_Thaa_MV'],
           'ht': ['ht_Latn_HT'],
           'zh-sg': ['zh_Latn_SG', 'zh_Hant_SG'],
           'ii': ['ii_Yiii_CN'],
           'fy': ['fy_Latn_NL'],
           'fo': ['fo_Latn_DK', 'fo_Latn_FO'],
           'ru': ['ru_Cyrl_BY',
            'ru_Cyrl_MN',
            'ru_Cyrl_IL',
            'ru_Cyrl_TM',
            'ru_Cyrl_US',
            'ru_Latn_KG',
            'ru_Cyrl_KZ',
            'ru_Cyrl_GE',
            'ru_Cyrl_LV',
            'ru_Cyrl_UZ',
            'ru_Latn_RU',
            'ru_Cyrl_UA',
            'ru_Cyrl_FI',
            'ru_Cyrl_KG',
            'ru_Cyrl_LT',
            'ru_Latn_BY',
            'ru_Cyrl_CN',
            'ru_Cyrl_PL',
            'ru_Cyrl_EE',
            'ru_Cyrl_SJ',
            'ru_Cyrl_MD',
            'ru_Latn_KZ',
            'ru_Cyrl_RU',
            'ru_Cyrl_BG',
            'ru_Cyrl_DE',
            'ru_Cyrl_TJ'],
           'bi': ['bi_Latn_VU'],
           'kk-cn': ['kk_Arab_CN'],
           'as': ['as_Beng_IN'],
           'uz-latn': ['uz_Latn_UZ'],
           'hr': ['hr_Latn_RS',
            'hr_Latn_IT',
            'hr_Latn_BA',
            'hr_Latn_HU',
            'hr_Latn_SI',
            'hr_Latn_AT',
            'hr_Latn_HR',
            'hr_Latn_DE'],
           'ku-arab': ['ku_Arab_LB'],
           'iu': ['iu_Latn_CA', 'iu_Cans_CA'],
           'nr': ['nr_Latn_ZA'],
           'ku': ['ku_Latn_AM', 'ku_Latn_TR', 'ku_Arab_LB'],
           'is': ['is_Latn_IS'],
           'sm': ['sm_Latn_WS', 'sm_Latn_AS'],
           'ff': ['ff_Adlm_NG',
            'ff_Adlm_NE',
            'ff_Latn_SN',
            'ff_Adlm_CM',
            'ff_Adlm_SL',
            'ff_Adlm_MR',
            'ff_Adlm_GN',
            'ff_Adlm_GH',
            'ff_Adlm_GM',
            'ff_Adlm_BF',
            'ff_Adlm_LR',
            'ff_Adlm_SN',
            'ff_Adlm_GW'],
           'ch': ['ch_Latn_GU', 'ch_Latn_MP'],
           'mi': ['mi_Latn_NZ'],
           'kk-latn': ['kk_Latn_KZ'],
           'zh-tw': ['zh_Latn_TW',
            'zh_Latn_TW',
            'zh_Latn_TW',
            'zh_Bopo_TW',
            'zh_Hant_TW',
            'zh_Hanb_TW'],
           'cr': ['cr_Cans_CA'],
           'bm': ['bm_Latn_ML', 'bm_Nkoo_ML'],
           'eo': ['eo_Latn_SM'],
           'ja-hani': ['ja_Hira_JP',
            'ja_Kana_JP',
            'ja_Latn_JP',
            'ja_Jpan_JP',
            'ja_Latn_JP',
            'ja_Latn_JP'],
           'ay': ['ay_Latn_PE', 'ay_Latn_BO'],
           'et': ['et_Latn_FI', 'et_Latn_EE'],
           'te': ['te_Telu_IN'],
           'nb': ['nb_Latn_NO', 'nb_Latn_SJ'],
           'dz': ['dz_Latn_BT', 'dz_Tibt_IN', 'dz_Tibt_BT'],
           'hy': ['hy_Armn_SY',
            'hy_Latn_AM',
            'hy_Armn_TR',
            'hy_Armn_LB',
            'hy_Armn_AM',
            'hy_Armn_IR',
            'hy_Cyrl_AM',
            'hy_Armn_CY',
            'hy_Armn_GE',
            'hy_Armn_RU'],
           'ny': ['ny_Latn_ZW', 'ny_Latn_MW', 'ny_Latn_ZM', 'ny_Latn_MZ'],
           'sg': ['sg_Latn_CF'],
           'ig': ['ig_Latn_NG'],
           'oc': ['oc_Latn_FR'],
           'ln': ['ln_Latn_CG', 'ln_Latn_CD', 'ln_Latn_CF', 'ln_Latn_AO'],
           'pt': ['pt_Latn_CV',
            'pt_Latn_PT',
            'pt_Latn_GW',
            'pt_Latn_CH',
            'pt_Latn_AG',
            'pt_Latn_FR',
            'pt_Latn_ST',
            'pt_Latn_TL',
            'pt_Latn_MO',
            'pt_Latn_MZ',
            'pt_Latn_BR',
            'pt_Latn_LU',
            'pt_Latn_AO',
            'pt_Latn_GQ'],
           'ty': ['ty_Latn_PF'],
           'ja-kana': ['ja_Kana_JP'],
           'hi': ['hi_Mahj_IN',
            'hi_Deva_ZA',
            'hi_Deva_FJ',
            'hi_Deva_NP',
            'hi_Latn_IN',
            'hi_Deva_UG',
            'hi_Deva_IN'],
           'el': ['el_Latn_CY',
            'el_Grek_GB',
            'el_Grek_TR',
            'el_Grek_DE',
            'el_Grek_EG',
            'el_Grek_RO',
            'el_Latn_GR',
            'el_Grek_AL',
            'el_Grek_CY',
            'el_Grek_GR',
            'el_Grek_UA',
            'el_Grek_IT'],
           'li': ['li_Latn_NL'],
           'zh-mo': ['zh_Hant_MO', 'zh_Latn_MO'],
           'my': ['my_Latn_MM', 'my_Mymr_MM', 'my_Mymr_BD'],
           'ky-arab': ['ky_Arab_CN'],
           'sk': ['sk_Latn_RS', 'sk_Latn_HU', 'sk_Latn_CZ', 'sk_Latn_SK'],
           'sw': ['sw_Latn_BI',
            'sw_Latn_CD',
            'sw_Latn_SO',
            'sw_Latn_UG',
            'sw_Latn_TZ',
            'sw_Latn_KE',
            'sw_Latn_ZA',
            'sw_Latn_YT',
            'sw_Latn_MZ'],
           'cv': ['cv_Cyrl_RU'],
           'eu': ['eu_Latn_FR', 'eu_Latn_ES'],
           'gv': ['gv_Latn_IM'],
           'cs': ['cs_Latn_SK', 'cs_Latn_CZ'],
           'za': ['za_Latn_CN'],
           'ms-arab': ['ms_Arab_CC', 'ms_Arab_ID', 'ms_Arab_BN'],
           'ik': ['ik_Latn_US'],
           'tn': ['tn_Latn_ZA', 'tn_Latn_NA', 'tn_Latn_BW', 'tn_Latn_ZW'],
           'mg': ['mg_Latn_MG'],
           'ku-latn': ['ku_Latn_AM', 'ku_Latn_TR'],
           'lo': ['lo_Latn_LA', 'lo_Laoo_LA'],
           'ro': ['ro_Latn_UA',
            'ro_Latn_RS',
            'ro_Latn_IL',
            'ro_Latn_HU',
            'ro_Latn_RO',
            'ro_Latn_MD'],
           'ky-cyrl': ['ky_Cyrl_KG'],
           'ne': ['ne_Deva_IN', 'ne_Latn_NP', 'ne_Deva_BT', 'ne_Deva_NP'],
           'lv': ['lv_Latn_LV'],
           'xh': ['xh_Latn_LS', 'xh_Latn_ZA'],
           'hu': ['hu_Latn_HU', 'hu_Hung_HU'],
           'sc': ['sc_Latn_IT'],
           'av': ['av_Cyrl_RU'],
           'vi': ['vi_Latn_VN', 'vi_Latn_CN', 'vi_Latn_US'],
           'pt-br': ['pt_Latn_BR'],
           'sd': ['sd_Deva_IN', 'sd_Arab_PK'],
           'ja-hira': ['ja_Hira_JP'],
           'ab': ['ab_Cyrl_TR', 'ab_Cyrl_GE'],
           'mk': ['mk_Cyrl_AL', 'mk_Latn_MK', 'mk_Cyrl_GR', 'mk_Cyrl_MK'],
           'hz': ['hz_Latn_NA'],
           'ml': ['ml_Mlym_AE',
            'ml_Mlym_IN',
            'ml_Mlym_SG',
            'ml_Mlym_GB',
            'ml_Mlym_QA',
            'ml_Mlym_IL',
            'ml_Mlym_MY',
            'ml_Mlym_BH'],
           'or': ['or_Orya_IN'],
           'ak': ['ak_Latn_GH'],
           'wa': ['wa_Latn_BE'],
           'aa': ['aa_Latn_ET', 'aa_Latn_DJ', 'aa_Latn_ER'],
           'da': ['da_Latn_DE', 'da_Latn_IS', 'da_Latn_GL', 'da_Latn_DK'],
           'rn': ['rn_Latn_BI'],
           'uz-cyrl': ['uz_Cyrl_UZ', 'uz_Cyrl_CN'],
           'sr-ec': ['sr_Latn_BA',
            'sr_Latn_RS',
            'sr_Latn_ME',
            'sr_Cyrl_RS',
            'sr_Latn_TR',
            'sr_Latn_RU',
            'sr_Latn_RO',
            'sr_Cyrl_BA',
            'sr_Cyrl_XK',
            'sr_Latn_XK'],
           'ia': ['ia_Latn_SE', 'ia_Latn_FR'],
           'ti': ['ti_Ethi_ER', 'ti_Ethi_ET', 'ti_Ethi_IL'],
           'am': ['am_Ethi_IL', 'am_Ethi_ET', 'am_Latn_ET'],
           'sv': ['sv_Latn_SE', 'sv_Latn_AX', 'sv_Latn_FI', 'sv_Latn_DK'],
           'fa-af': ['fa_Arab_AF', 'fa_Latn_AF'],
           've': ['ve_Latn_ZW', 've_Latn_ZA'],
           'id': ['id_Latn_ID', 'id_Latn_NL'],
           'lg': ['lg_Latn_UG'],
           'zh-hk': ['zh_Hant_HK', 'zh_Latn_HK'],
           'fj': ['fj_Latn_FJ'],
           'th': ['th_Thai_TH', 'th_Latn_TH'],
           'qu': ['qu_Latn_PE', 'qu_Latn_EC', 'qu_Latn_BO'],
           'es': ['es_Latn_BZ',
            'es_Latn_UY',
            'es_Latn_PH',
            'es_Latn_CW',
            'es_Latn_DE',
            'es_Latn_AD',
            'es_Latn_MX',
            'es_Latn_SV',
            'es_Latn_IC',
            'es_Latn_EC',
            'es_Latn_VE',
            'es_Latn_PE',
            'es_Latn_MA',
            'es_Latn_HN',
            'es_Latn_NI',
            'es_Latn_RO',
            'es_Latn_AR',
            'es_Latn_PT',
            'es_Latn_SX',
            'es_Latn_GT',
            'es_Latn_FR',
            'es_Latn_CR',
            'es_Latn_PY',
            'es_Latn_PR',
            'es_Latn_CO',
            'es_Latn_BR',
            'es_Latn_PA',
            'es_Latn_ES',
            'es_Latn_DO',
            'es_Latn_GQ',
            'es_Latn_EA',
            'es_Latn_CL',
            'es_Latn_TT',
            'es_Latn_GI',
            'es_Latn_US',
            'es_Latn_CU',
            'es_Latn_BO'],
           'tt': ['tt_Cyrl_RU'],
           'kn': ['kn_Knda_IN'],
           'br': ['br_Latn_FR'],
           'ko': ['ko_Hang_KR',
            'ko_Latn_KR',
            'ko_Kore_JP',
            'ko_Kore_KR',
            'ko_Latn_KR',
            'ko_Latn_KR',
            'ko_Kore_BR',
            'ko_Kore_CN',
            'ko_Jamo_KR',
            'ko_Kore_KP',
            'ko_Kore_US',
            'ko_Latn_KP'],
           'ks-arab': ['ks_Arab_PK', 'ks_Arab_IN', 'ks_Arab_GB'],
           'zh': ['zh_Hant_US',
            'zh_Hant_MY',
            'zh_Hant_GB',
            'zh_Hant_ID',
            'zh_Hant_PH',
            'zh_Hant_VN',
            'zh_Hant_HK',
            'zh_Hant_MN',
            'zh_Latn_CN',
            'zh_Hant_SR',
            'zh_Hant_GF',
            'zh_Hant_BN',
            'zh_Latn_CN',
            'zh_Hant_PA',
            'zh_Latn_TW',
            'zh_Hant_AU',
            'zh_Latn_TW',
            'zh_Latn_CN',
            'zh_Hant_MO',
            'zh_Hant_PF',
            'zh_Hant_TH',
            'zh_Latn_HK',
            'zh_Latn_SG',
            'zh_Latn_TW',
            'zh_Hans_CN',
            'zh_Hant_CN',
            'zh_Latn_MO',
            'zh_Bopo_TW',
            'zh_Hant_SG',
            'zh_Hani_CN',
            'zh_Hant_TW',
            'zh_Hanb_TW'],
           'zh-cn': ['zh_Latn_CN',
            'zh_Latn_CN',
            'zh_Latn_CN',
            'zh_Hans_CN',
            'zh_Hant_CN',
            'zh_Hani_CN'],
           'sr': ['sr_Latn_BA',
            'sr_Latn_RS',
            'sr_Latn_ME',
            'sr_Cyrl_RS',
            'sr_Latn_TR',
            'sr_Latn_RU',
            'sr_Latn_RO',
            'sr_Cyrl_BA',
            'sr_Cyrl_XK',
            'sr_Latn_XK'],
           'na': ['na_Latn_NR'],
           'cu': ['cu_Cyrl_RU'],
           'cy': ['cy_Latn_AR', 'cy_Latn_GB'],
           'ho': ['ho_Latn_PG'],
           'ss': ['ss_Latn_SZ', 'ss_Latn_ZA', 'ss_Latn_LS'],
           'tg': ['tg_Arab_PK', 'tg_Latn_TJ', 'tg_Cyrl_TJ'],
           'se': ['se_Latn_SE', 'se_Latn_FI', 'se_Latn_NO'],
           'yi': ['yi_Hebr_CA',
            'yi_Hebr_UA',
            'yi_Hebr_SE',
            'yi_Hebr_GB',
            'yi_Hebr_IL',
            'yi_Hebr_US'],
           'ka': ['ka_Geor_TR', 'ka_Latn_GE', 'ka_Geor_GE', 'ka_Geor_IR'],
           'zh-my': ['zh_Hant_MY'],
           'sn': ['sn_Latn_ZW'],
           'fr-ca': ['fr_Latn_CA'],
           'ug-latn': ['ug_Arab_CN', 'ug_Cyrl_MN', 'ug_Cyrl_KZ'],
           'ki': ['ki_Latn_KE'],
           'to': ['to_Latn_TO'],
           'en': ['en_Latn_IO',
            'en_Latn_AE',
            'en_Latn_GD',
            'en_Latn_KN',
            'en_Latn_PW',
            'en_Latn_MY',
            'en_Latn_VG',
            'en_Latn_DE',
            'en_Latn_GI',
            'en_Latn_YE',
            'en_Latn_GM',
            'en_Latn_GU',
            'en_Latn_AT',
            'en_Latn_DK',
            'en_Latn_SX',
            'en_Latn_CA',
            'en_Latn_BB',
            'en_Latn_PK',
            'en_Latn_LK',
            'en_Latn_NG',
            'en_Latn_MG',
            'en_Latn_JO',
            'en_Latn_AW',
            'en_Latn_VC',
            'en_Latn_MA',
            'en_Latn_CZ',
            'en_Latn_SK',
            'en_Latn_JM',
            'en_Latn_CM',
            'en_Latn_UG',
            'en_Latn_DM',
            'en_Latn_SC',
            'en_Latn_PA',
            'en_Latn_BN',
            'en_Latn_LV',
            'en_Latn_IQ',
            'en_Latn_FK',
            'en_Latn_CC',
            'en_Latn_PL',
            'en_Latn_ET',
            'en_Latn_PT',
            'en_Latn_SG',
            'en_Latn_SZ',
            'en_Latn_TR',
            'en_Latn_US',
            'en_Latn_MS',
            'en_Latn_BM',
            'en_Latn_LU',
            'en_Latn_MO',
            'en_Latn_IT',
            'en_Latn_GR',
            'en_Latn_CL',
            'en_Latn_SE',
            'en_Latn_BW',
            'en_Shaw_GB',
            'en_Latn_NU',
            'en_Latn_FJ',
            'en_Latn_TO',
            'en_Latn_MU',
            'en_Latn_PH',
            'en_Latn_SD',
            'en_Latn_FM',
            'en_Latn_MT',
            'en_Latn_AR',
            'en_Latn_RO',
            'en_Latn_BR',
            'en_Latn_ZM',
            'en_Latn_SI',
            'en_Latn_DO',
            'en_Latn_GG',
            'en_Latn_LR',
            'en_Latn_TC',
            'en_Latn_PN',
            'en_Latn_VI',
            'en_Latn_NA',
            'en_Latn_EG',
            'en_Latn_NL',
            'en_Latn_LT',
            'en_Latn_BD',
            'en_Latn_IE',
            'en_Latn_KI',
            'en_Latn_KY',
            'en_Latn_NZ',
            'en_Latn_SS',
            'en_Latn_LS',
            'en_Latn_TH',
            'en_Latn_ES',
            'en_Latn_CK',
            'en_Latn_AC',
            'en_Latn_IM',
            'en_Latn_HU',
            'en_Latn_BE',
            'en_Latn_AU',
            'en_Latn_ZA',
            'en_Latn_EE',
            'en_Latn_TA',
            'en_Latn_TZ',
            'en_Latn_SL',
            'en_Latn_LC',
            'en_Latn_BT',
            'en_Latn_TT',
            'en_Latn_BZ',
            'en_Latn_FI',
            'en_Latn_KZ',
            'en_Latn_GB',
            'en_Latn_NF',
            'en_Latn_ZW',
            'en_Latn_WS',
            'en_Latn_CH',
            'en_Latn_SB',
            'en_Latn_BI',
            'en_Latn_HK',
            'en_Latn_DG',
            'en_Latn_VU',
            'en_Latn_DZ',
            'en_Latn_GY',
            'en_Latn_NP',
            'en_Latn_HN',
            'en_Latn_IN',
            'en_Latn_MP',
            'en_Latn_TV',
            'en_Latn_JE',
            'en_Latn_ER',
            'en_Latn_BS',
            'en_Latn_SH',
            'en_Latn_NR',
            'en_Latn_MH',
            'en_Latn_PR',
            'en_Latn_PM',
            'en_Latn_KE',
            'en_Latn_MX',
            'en_Latn_CY',
            'en_Latn_RW',
            'en_Latn_MW',
            'en_Latn_IL',
            'en_Latn_BG',
            'en_Latn_PG',
            'en_Latn_AI',
            'en_Latn_HR',
            'en_Latn_AS',
            'en_Latn_BA',
            'en_Latn_CX',
            'en_Latn_GH',
            'en_Latn_LB',
            'en_Latn_AG',
            'en_Latn_TK',
            'en_Latn_FR',
            'en_Latn_UM',
            'en_Latn_CN'],
           'ja-hrkt': ['ja_Hira_JP',
            'ja_Kana_JP',
            'ja_Latn_JP',
            'ja_Jpan_JP',
            'ja_Latn_JP',
            'ja_Latn_JP'],
           'nv': ['nv_Latn_US'],
           'an': ['an_Latn_ES'],
           'nl-be': ['nl_Latn_BE'],
           'st': ['st_Latn_ZA', 'st_Latn_LS'],
           'de-ch': ['de_Latn_CH'],
           'ko-kr': ['ko_Hang_KR',
            'ko_Latn_KR',
            'ko_Kore_KR',
            'ko_Latn_KR',
            'ko_Latn_KR',
            'ko_Jamo_KR'],
           'zh-hans': ['zh_Hans_CN'],
           'mn': ['mn_Mong_CN', 'mn_Cyrl_MN', 'mn_Latn_MN'],
           'ms': ['ms_Arab_CC',
            'ms_Latn_MY',
            'ms_Arab_ID',
            'ms_Arab_BN',
            'ms_Latn_BN'],
           'kg': ['kg_Latn_CD'],
           'tt-cyrl': ['tt_Cyrl_RU'],
           'ur': ['ur_Arab_IN', 'ur_Latn_PK', 'ur_Arab_PK', 'ur_Arab_MU'],
           'ar': ['ar_Arab_MA',
            'ar_Latn_YE',
            'ar_Arab_SD',
            'ar_Latn_SA',
            'ar_Latn_MA',
            'ar_Arab_MR',
            'ar_Arab_EG',
            'ar_Arab_CM',
            'ar_Latn_IL',
            'ar_Latn_DZ',
            'ar_Arab_ML',
            'ar_Latn_sa',
            'ar_Arab_NE',
            'ar_Latn_TD',
            'ar_Arab_LB',
            'ar_Arab_IR',
            'ar_Arab_TN',
            'ar_Latn_DJ',
            'ar_Arab_SY',
            'ar_Arab_SO',
            'ar_Latn_MR',
            'ar_Arab_KE',
            'ar_Latn_IQ',
            'ar_Arab_OM',
            'ar_Arab_CY',
            'ar_Arab_YE',
            'ar_Arab_LY',
            'ar_Latn_QA',
            'ar_Arab_IL',
            'ar_Arab_KW',
            'ar_Arab_DJ',
            'ar_Latn_SD',
            'ar_Arab_IQ',
            'ar_Latn_ER',
            'ar_Arab_JO',
            'ar_Arab_AE',
            'ar_Latn_LB',
            'ar_Latn_EH',
            'ar_Arab_NG',
            'ar_Latn_LY',
            'ar_Latn_AE',
            'ar_Arab_TR',
            'ar_Arab_SS',
            'ar_Arab_PS',
            'ar_Arab_QA',
            'ar_Arab_SA',
            'ar_Arab_KM',
            'ar_Latn_KW',
            'ar_Latn_BH',
            'ar_Arab_BH',
            'ar_Latn_SY',
            'ar_Arab_EH',
            'ar_Arab_TD',
            'ar_Latn_JO',
            'ar_Arab_TJ',
            'ar_Latn_TN',
            'ar_Latn_KM',
            'ar_Latn_PS',
            'ar_Arab_ER',
            'ar_Arab_DZ',
            'ar_Latn_OM',
            'ar_Latn_SO',
            'ar_Latn_EG'],
           'rm': ['rm_Latn_CH'],
           'kk-tr': ['kk_Arab_TR'],
           'ts': ['ts_Latn_MZ', 'ts_Latn_SZ', 'ts_Latn_ZA'],
           'lb': ['lb_Latn_LU'],
           'yo': ['yo_Latn_NG', 'yo_Latn_BJ'],
           'de': ['de_Latn_PY',
            'de_Latn_DE',
            'de_Latn_SK',
            'de_Latn_CH',
            'de_Latn_FI',
            'de_Latn_SI',
            'de_Latn_GR',
            'de_Latn_DK',
            'de_Latn_FR',
            'de_Latn_RO',
            'de_Latn_HU',
            'de_Latn_NL',
            'de_Latn_AT',
            'de_Latn_BE',
            'de_Latn_CZ',
            'de_Latn_US',
            'de_Latn_CA',
            'de_Latn_LT',
            'de_Latn_IT',
            'de_Latn_BG',
            'de_Latn_GB',
            'de_Latn_PL',
            'de_Latn_LI',
            'de_Latn_BR',
            'de_Latn_NA',
            'de_Latn_KZ',
            'de_Latn_LU'],
           'he': ['he_Latn_IL', 'he_Hebr_IL'],
           'km': ['km_Latn_KH', 'km_Khmr_KH'],
           'nl': ['nl_Latn_SX',
            'nl_Latn_CW',
            'nl_Latn_FR',
            'nl_Latn_AW',
            'nl_Latn_BQ',
            'nl_Latn_BE',
            'nl_Latn_DE',
            'nl_Latn_NL',
            'nl_Latn_SR'],
           'en-us': ['en_Latn_US'],
           'fi': ['fi_Latn_SE', 'fi_Latn_RU', 'fi_Latn_EE', 'fi_Latn_FI'],
           'pl': ['pl_Latn_PL',
            'pl_Latn_DE',
            'pl_Latn_IL',
            'pl_Latn_UA',
            'pl_Latn_RO',
            'pl_Latn_CZ',
            'pl_Latn_SK'],
           'ce': ['ce_Cyrl_RU'],
           'de-at': ['de_Latn_AT'],
           'fa': ['fa_Arab_TJ',
            'fa_Arab_PK',
            'fa_Arab_AF',
            'fa_Arab_OM',
            'fa_Arab_QA',
            'fa_Arab_AE',
            'fa_Latn_AF',
            'fa_Latn_IR',
            'fa_Arab_IQ',
            'fa_Arab_IR'],
           'rw': ['rw_Latn_RW', 'rw_Latn_CD', 'rw_Latn_UG'],
           'ks': ['ks_Arab_PK', 'ks_Arab_IN', 'ks_Arab_GB'],
           'la': ['la_Latn_VA'],
           'it': ['it_Latn_GB',
            'it_Latn_SI',
            'it_Latn_US',
            'it_Latn_AT',
            'it_Latn_BR',
            'it_Latn_AU',
            'it_Latn_FR',
            'it_Latn_CH',
            'it_Latn_HR',
            'it_Latn_CA',
            'it_Latn_IT',
            'it_Latn_VA',
            'it_Latn_DE',
            'it_Latn_SM',
            'it_Latn_MT'],
           'ks-deva': ['ks_Arab_PK', 'ks_Arab_IN', 'ks_Arab_GB'],
           'kj': ['kj_Latn_NA'],
           'kk-kz': ['kk_Latn_KZ', 'kk_Cyrl_KZ'],
           'fr': ['fr_Latn_US',
            'fr_Latn_GQ',
            'fr_Latn_NL',
            'fr_Latn_FR',
            'fr_Latn_LU',
            'fr_Latn_IT',
            'fr_Latn_KM',
            'fr_Latn_CI',
            'fr_Latn_PT',
            'fr_Latn_TD',
            'fr_Latn_CM',
            'fr_Latn_WF',
            'fr_Latn_CY',
            'fr_Latn_SN',
            'fr_Latn_GR',
            'fr_Latn_MF',
            'fr_Latn_MC',
            'fr_Latn_MA',
            'fr_Latn_MQ',
            'fr_Latn_CD',
            'fr_Latn_VU',
            'fr_Latn_NC',
            'fr_Latn_DJ',
            'fr_Latn_HU',
            'fr_Latn_GN',
            'fr_Latn_AD',
            'fr_Latn_GF',
            'fr_Latn_MR',
            'fr_Latn_CF',
            'fr_Latn_PM',
            'fr_Dupl_FR',
            'fr_Latn_RO',
            'fr_Latn_RE',
            'fr_Latn_MU',
            'fr_Latn_ML',
            'fr_Latn_BF',
            'fr_Latn_CH',
            'fr_Latn_HT',
            'fr_Latn_BJ',
            'fr_Latn_CG',
            'fr_Latn_GP',
            'fr_Latn_DE',
            'fr_Latn_BI',
            'fr_Latn_YT',
            'fr_Latn_MG',
            'fr_Latn_SY',
            'fr_Latn_TN',
            'fr_Latn_LB',
            'fr_Latn_MT',
            'fr_Latn_RW',
            'fr_Latn_GA',
            'fr_Latn_DZ',
            'fr_Latn_PF',
            'fr_Latn_SC',
            'fr_Latn_GB',
            'fr_Latn_NE',
            'fr_Latn_BE',
            'fr_Latn_IE',
            'fr_Latn_AT',
            'fr_Latn_CA',
            'fr_Latn_TG',
            'fr_Latn_TF',
            'fr_Latn_BL',
            'fr_Brai_FR'],
           'ug-arab': ['ug_Arab_CN'],
           'ta': ['ta_Taml_MY',
            'ta_Taml_IN',
            'ta_Latn_SG',
            'ta_Taml_SG',
            'ta_Latn_LK',
            'ta_Taml_MU',
            'ta_Taml_LK',
            'ta_Taml_RE'],
           'ca': ['ca_Latn_AD', 'ca_Latn_ES', 'ca_Latn_FR', 'ca_Latn_IT'],
           'ps': ['ps_Arab_IR',
            'ps_Arab_AE',
            'ps_Arab_AF',
            'ps_Latn_AF',
            'ps_Arab_PK'],
           'zu': ['zu_Latn_LS',
            'zu_Latn_MW',
            'zu_Latn_MZ',
            'zu_Latn_ZA',
            'zu_Latn_SZ'],
           'ga': ['ga_Latn_GB', 'ga_Latn_IE'],
           'af': ['af_Latn_NA', 'af_Latn_BW', 'af_Latn_ZA'],
           'en-gb': ['en_Shaw_GB', 'en_Latn_GB'],
           'uz': ['uz_Latn_UZ', 'uz_Arab_AF', 'uz_Cyrl_UZ', 'uz_Cyrl_CN'],
           'kk-arab': ['kk_Arab_MN',
            'kk_Arab_CN',
            'kk_Arab_AF',
            'kk_Arab_TR',
            'kk_Arab_IR'],
           'mh': ['mh_Latn_MH'],
           'sl': ['sl_Latn_IT', 'sl_Latn_HU', 'sl_Latn_AT', 'sl_Latn_SI'],
           'zh-hant': ['zh_Hant_US',
            'zh_Hant_MY',
            'zh_Hant_GB',
            'zh_Hant_ID',
            'zh_Hant_PH',
            'zh_Hant_VN',
            'zh_Hant_HK',
            'zh_Hant_MN',
            'zh_Hant_SR',
            'zh_Hant_GF',
            'zh_Hant_BN',
            'zh_Hant_PA',
            'zh_Hant_AU',
            'zh_Hant_MO',
            'zh_Hant_PF',
            'zh_Hant_TH',
            'zh_Hant_CN',
            'zh_Hant_SG',
            'zh_Hant_TW'],
           'az': ['az_Cyrl_RU',
            'az_Arab_TR',
            'az_Arab_AM',
            'az_Cyrl_AZ',
            'az_Arab_IQ',
            'az_Latn_AZ',
            'az_Arab_IR'],
           'si': ['si_Sinh_LK', 'si_Latn_LK'],
           'sq': ['sq_Latn_MK',
            'sq_Latn_AL',
            'sq_Latn_ME',
            'sq_Latn_XK',
            'sq_Elba_AL',
            'sq_Latn_RS',
            'sq_Latn_GR',
            'sq_Latn_TR'],
           'wo': ['wo_Latn_SN', 'wo_Latn_MR'],
           'en-ca': ['en_Latn_CA'],
           'ky': ['ky_Arab_CN', 'ky_Latn_KG', 'ky_Latn_TR', 'ky_Cyrl_KG'],
           'kw': ['kw_Latn_GB'],
           'ha': ['ha_Latn_NE', 'ha_Arab_SD', 'ha_Arab_CM', 'ha_Arab_NG'],
           'gd': ['gd_Latn_GB'],
           'mt': ['mt_Latn_MT'],
           'uk': ['uk_Cyrl_SK',
            'uk_Cyrl_UA',
            'uk_Cyrl_RS',
            'uk_Cyrl_MD',
            'uk_Latn_UA',
            'uk_Cyrl_PL'],
           'ba': ['ba_Cyrl_RU'],
           'lt': ['lt_Latn_LT', 'lt_Latn_PL'],
           'gn': ['gn_Latn_AR', 'gn_Latn_PY', 'gn_Latn_BO'],
           'tr': ['tr_Latn_CY',
            'tr_Latn_GR',
            'tr_Latn_MK',
            'tr_Latn_TR',
            'tr_Latn_BG',
            'tr_Latn_DE',
            'tr_Latn_UA',
            'tr_Latn_NL',
            'tr_Latn_RO',
            'tr_Latn_UZ'],
           'az-cyrl': ['az_Cyrl_RU', 'az_Cyrl_AZ'],
           'sr-el': ['sr_Latn_BA',
            'sr_Latn_RS',
            'sr_Latn_ME',
            'sr_Cyrl_RS',
            'sr_Latn_TR',
            'sr_Latn_RU',
            'sr_Latn_RO',
            'sr_Cyrl_BA',
            'sr_Cyrl_XK',
            'sr_Latn_XK'],
           'tt-latn': ['tt_Cyrl_RU'],
           'tg-latn': ['tg_Latn_TJ'],
           'os': ['os_Cyrl_GE', 'os_Cyrl_RU'],
           'gl': ['gl_Latn_ES', 'gl_Latn_PT'],
           'gu': ['gu_Gujr_KE', 'gu_Gujr_IN'],
           'nn': ['nn_Latn_NO'],
           'kl': ['kl_Latn_GL', 'kl_Latn_DK']}

